server:
  port: 1000

jwt:
  secret: javainuse


spring:
  datasource:
    username: postgres
    password: 3580
    url: jdbc:postgresql://localhost:5432/scalableDB
    platform: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  cache:
    type: redis
    redis:
      cache-null-values: true
  cloud:
    azure:
      credential:
        managed-identity-enabled: true
        client-id: ${AZURE_CLIENT_ID}
      servicebus:
        namespace: "localhost"
        entity-type: queue
        processor:
          max-concurrent-calls: 1
          prefetch-count: 1


logging:
  level:
    org:
      springframework:
        cache: Trace