server:
  port: 2000

spring:
  cloud:
    azure:
      credential:
        managed-identity-enabled: true
        client-id: ${AZURE_CLIENT_ID}
      servicebus:
        namespace: "localhost"
        entity-type: queue
        processor:
          max-concurrent-calls: 1
          prefetch-count: 1
   
