spring:
  cloud:
    azure:
      credential:
        managed-identity-enabled: true
        client-id: ${AZURE_CLIENT_ID}
      servicebus:
        namespace: "localhost"
        entity-type: queue
        consumer:
          session-enabled: true


